name: Build and Push Docker Image

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: utkarshraj29/ccid_onefail:latest
          file: ./dockerfile
          
  test_image:
    name: Test Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull utkarshraj29/ccid_onefail:latest

      - name: Execute Docker image and test
        run: |
          OUTPUT=$(docker run --rm utkarshraj29/ccid_onefail:latest)
          echo "Score: $OUTPUT"
          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then
            echo "Insufficient Accuracy"
            exit 1
          fi
